### ISSUE TITLE
HAProxy defunct process in container 

### ISSUE THREAD

**Issue by joshughes** [tnolet/haproxy-rest#3]
https://github.com/QubitProducts/bamboo/issues/31

Looks like this same bug exists in this project. We are seeing defunct processes in the container whenever we reconfigure haproxy.

**Comment by tnolet** [comment]
@joshughes This doesn't happen when running on OSX Yosemite/Darwin, but I do see it in Ubuntu Linux boxes. It should not be harmful, but it is kinda disturbing. Will look at a way to fix this

**Comment by joshughes** [comment]
@tnolet https://github.com/itriage/haproxy-rest/tree/defunkt_kill I was able to fix it in this branch... I could not get the Kafka stuff to compile and since we are not using it I just removed it. Basically I reimplemented the fix Bamboo put in place.

**Comment by tnolet** [comment]
that’s awesome! Any chance you could make a pull request for it?

Tim Nolet
co-founder / CTO
tim@magnetic.io

**Comment by tnolet** [comment]
@joshughes 

Will import the fix into our "next-gen" haproxy-rest which I'm currently working on. We'll open source it somewhere in march. It is a total rewrite with a nicer structure, SSE streaming of metrics and some more nice REST features. Will close this for now.
